#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ -d "$cachedir" ] || mkdir -p "$cachedir"

IFS=:
if [ ! -s "$cache" ] || stest -dqr -n "$cache" $PATH 2>/dev/null; then
	stest -flx $PATH 2>/dev/null | sort -u | tee "$cache"
else
	cat "$cache"
fi
